src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="user")
     */
    private $commandes;

    /**
     * @ORM\OneToMany(targetEntity=Publication::class, mappedBy="user")
     */
    private $publications;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomProducteur;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $numeroProducteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    // public function hydrate(array $init)
    // {
    //     foreach ($init as $key => $value) {
    //         $method = "set" . ucfirst($key);
    //         if (method_exists($this, $method)) {
    //             $this->$method($value);
    //         }
    //     }
    // }
    public function __construct()
    {
        // $this->hydrate ($init);
        $this->commandes = new ArrayCollection();
        $this->publications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Publication[]
     */
    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): self
    {
        if (!$this->publications->contains($publication)) {
            $this->publications[] = $publication;
            $publication->setUser($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): self
    {
        if ($this->publications->removeElement($publication)) {
            // set the owning side to null (unless already changed)
            if ($publication->getUser() === $this) {
                $publication->setUser(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNomProducteur(): ?string
    {
        return $this->nomProducteur;
    }

    public function setNomProducteur(?string $nomProducteur): self
    {
        $this->nomProducteur = $nomProducteur;

        return $this;
    }

    public function getNumeroProducteur(): ?string
    {
        return $this->numeroProducteur;
    }

    public function setNumeroProducteur(?string $numeroProducteur): self
    {
        $this->numeroProducteur = $numeroProducteur;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MembreController extends AbstractController
{
    // #[Route('/membre/login', name: 'login')]
    // public function login(): Response
    // {
    //     return $this->render('membre/login.html.twig');
    // }
    #[Route('/membre/accueil/inscription', name: 'accueilInscription')]
    public function accueilInscription(): Response
    {
        return $this->render('membre/accueilInscription.html.twig');
    }
    // #[Route('/membre/inscription/client', name: 'inscriptionClient')]
    // public function inscription(): Response
    // {
    //     return $this->render('membre/inscriptionClient.html.twig');
    // }
    #[Route('/membre/inscription/producteur', name: 'inscriptionProducteur')]
    public function inscriptionProducteur(): Response
    {
        return $this->render('membre/inscriptionProducteur.html.twig');
    }
    #[Route('/membre/profil', name: 'profil')]
    public function profil(): Response
    {
        $this->getUser();
        return $this->render('membre/profil.html.twig');
    }
}

templates/membre/accueilInscription.html.twig
{% extends "layout.html.twig" %}

{% block content %}	
<link rel="stylesheet" href="{{ asset ('assets/css/accueilInscription.css') }}">
<div id="fh5co-started">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>Inscription</h2>
					{# <p>Just stay tune for our latest Product. Now you can subscribe</p> #}
				</div>
			</div>
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2">
					<form class="form-inline">
						<div class="col-md-6 col-sm-6">
							<div class="form-group">
                            <button type="submit" class="btn btn-default btn-block"><a href = "{{ path ('inscriptionClient') }}">Client</a></button>
								
							</div>
						</div>
						<div class="col-md-6 col-sm-6">
							<button type="submit" class="btn btn-default btn-block"><a href = "{{ path ('inscriptionProducteur') }}">Producteur</a></button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/membre/inscription.html.twig
{% extends "layout.html.twig" %}

{% block content %}	
<link rel="stylesheet" href="{{ asset ('assets/css/inscription.css') }}">
	<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background: radial-gradient(circle, rgba(147,203,85,1) 78%, rgba(134,193,133,1) 100%);">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Inscription</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card1">
        <form onsubmit="event.preventDefault()" class="box1">
          {# <h1>Login</h1> #}
          <p class="text-muted">Veuillez saisir vos données</p>
          <input type="text" name="" placeholder="Nom" />
          <input type="text" name="" placeholder="Prénom" />
          <input type="text" name="" placeholder="Rue" />
          <input type="text" name="" placeholder="Numéro" />
          <input type="text" name="" placeholder="CP" />
          <input type="text" name="" placeholder="Ville" />
          <input type="text" name="" placeholder="Email" />
          <input type="text" name="" placeholder="login" />
          <input type="password" name="" placeholder="Mot de passe" />
          <a class="forgot text-muted" href="{{ path ('login') }}">Vous avez déjà un compte ?</a>
          <input type="submit" name="" value="S'inscrire" href="" />
          <div class="col-md-12">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
    
{% endblock %}

templates/membre/profil.html.twig
{% extends "layout.html.twig" %}

{% block content %}	
<link rel="stylesheet" href="{{ asset ('assets/css/profil.css') }}">
{% if is_granted('ROLE_CLIENT') %}


	<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background: radial-gradient(circle, rgba(147,203,85,1) 78%, rgba(134,193,133,1) 100%);">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Client</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

<!------ Include the above in your HEAD tag ---------->
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                       {{ app.user.prenom}} {{ app.user.nom}} 
                                    </h5>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>ACTIONS</p>
                            <a href="{{ path ('produitsAchetes') }}">Produits achetés</a><br/>
                            <p>AUTRES</p>
                            <a href="{{ path ('app_logout') }}">Logout</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Login</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ app.user.username }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Téléphone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>123 456 7890</p>
                                            </div>
                                        </div>
                                           <div class="row">
                                            <div class="col-md-6">
                                                <label>Adresse</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ app.user.rue }}, {{ app.user.cp }} {{ app.user.ville }}</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>

{% else %}

	<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background: radial-gradient(circle, rgba(147,203,85,1) 78%, rgba(134,193,133,1) 100%);">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Producteur</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

<!------ Include the above in your HEAD tag ---------->
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                            <h2>
                                {{ app.user.nomProducteur}}
                            </h2>
                                    <h5>
                                       {{ app.user.prenom}} {{ app.user.nom}} 
                                    </h5>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>ACTIONS</p>
                            <a href="{{ path ('produitsPublies') }}">Produits publiés</a><br/>
                            <p>AUTRES</p>
                            <a href="{{ path ('app_logout') }}">Logout</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Login</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ app.user.username }}</p>
                                            </div>
                                        </div>
                                          <div class="row">
                                            <div class="col-md-6">
                                                <label>Numéro producteur</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ app.user.numeroProducteur }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Téléphone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>123 456 7890</p>
                                            </div>
                                        </div>
                                           <div class="row">
                                            <div class="col-md-6">
                                                <label>Adresse</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ app.user.rue }}, {{ app.user.cp }} {{ app.user.ville }}</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>



        {% endif %}
    {% endblock %}